# This file was generated by GoReleaser. DO NOT EDIT.
class Sshststuff < Formula
  desc "TODO"
  homepage "https://ssh.st"
  version "0.11"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sshst/sshststuff/releases/download/0.11/sshststuff_0.11_Darwin_x86_64.tar.gz"
    sha256 "3971322af2e6f0ad6967b5b589bb3cf8b5c3a43fa6296f1ea1a9c1ed7fcb5574"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sshst/sshststuff/releases/download/0.11/sshststuff_0.11_Linux_x86_64.tar.gz"
      sha256 "e9a9d1e0c5749056c25ead6e4e570e440abdd307aa6f9efcd4e15e2e61b86b48"
    end
  end

  def install
    bin.install "sshst"
  end
end
