# This file was generated by GoReleaser. DO NOT EDIT.
class Sshststuff < Formula
  desc "TODO"
  homepage "https://ssh.st"
  version "0.6.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sshst/sshststuff/releases/download/0.6.0/sshststuff_0.6.0_Darwin_x86_64.tar.gz"
    sha256 "247e13fb39e4ee0905485ff250be4dfd18ac9d6b358f069dd318be4c3d8e1d09"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sshst/sshststuff/releases/download/0.6.0/sshststuff_0.6.0_Linux_x86_64.tar.gz"
      sha256 "60f3cf2b98ef31a8152888d50d846930f09c6ae9c24d880ec5b1cc58b547537f"
    end
  end

  def install
    bin.install "sshststuff"
  end
end
