# This file was generated by GoReleaser. DO NOT EDIT.
class Sshst < Formula
  desc "TODO"
  homepage "https://ssh.st"
  version "0.17"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sshst/sshststuff/releases/download/0.17/sshst_0.17_Darwin_x86_64.tar.gz"
    sha256 "bcaa3895abb6686cccea56c4ebf21c3366f0258b9057385a3295a80ec8d071c7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sshst/sshststuff/releases/download/0.17/sshst_0.17_Linux_x86_64.tar.gz"
      sha256 "ca1368cc6fc503ad8e279da667a8e09856157c3a4712ad3c88eae39d1f140b28"
    end
  end

  def install
    bin.install "sshst"
  end
end
